import { MenuItem, Order } from './types';

export const MENU_ITEMS: MenuItem[] = [
  // Starters
  {
    id: 'spring-rolls',
    name: 'Spring Rolls',
    description: 'Crispy golden rolls filled with cabbage, carrot, and fresh vegetables',
    price: 4.99,
    image: '/menu-items/spring-rolls.png',
    category: 'Starters',
    spiceLevel: 'mild',
    vegType: 'veg',
    servings: 4,
    preparationTime: 10,
  },
  {
    id: 'crispy-wonton',
    name: 'Crispy Wonton',
    description: 'Golden fried wontons served with sweet and sour sauce',
    price: 5.99,
    image: '/menu-items/crispy-wonton.jpg',
    category: 'Starters',
    spiceLevel: 'mild',
    vegType: 'non_veg',
    servings: 6,
    preparationTime: 12,
  },
  {
    id: 'vegetable-samosa',
    name: 'Vegetable Samosa',
    description: 'Crispy triangular pastries filled with spiced potatoes and peas',
    price: 3.99,
    image: '/menu-items/samosa.jpg',
    category: 'Starters',
    spiceLevel: 'medium',
    vegType: 'veg',
    servings: 3,
    preparationTime: 8,
  },
  {
    id: 'prawn-toast',
    name: 'Prawn Toast',
    description: 'Succulent prawns on crispy bread slices with sesame seeds',
    price: 6.99,
    image: '/menu-items/prawn-toast.jpg',
    category: 'Starters',
    spiceLevel: 'medium',
    vegType: 'non_veg',
    servings: 4,
    preparationTime: 12,
  },

  // Soups
  {
    id: 'hot-sour-soup',
    name: 'Hot & Sour Soup',
    description: 'Tangy and spicy soup with mushrooms, bamboo shoots, and tofu',
    price: 3.99,
    image: '/menu-items/hot-sour-soup.jpg',
    category: 'Soups',
    spiceLevel: 'hot',
    vegType: 'veg',
    servings: 2,
    preparationTime: 10,
  },
  {
    id: 'egg-drop-soup',
    name: 'Egg Drop Soup',
    description: 'Silky smooth broth with ribbons of egg and fresh scallions',
    price: 2.99,
    image: '/menu-items/egg-drop-soup.jpg',
    category: 'Soups',
    spiceLevel: 'mild',
    vegType: 'veg',
    servings: 2,
    preparationTime: 8,
  },
  {
    id: 'wonton-soup',
    name: 'Wonton Soup',
    description: 'Delicate wontons filled with pork and shrimp in aromatic broth',
    price: 4.49,
    image: '/menu-items/wonton-soup.jpg',
    category: 'Soups',
    spiceLevel: 'mild',
    vegType: 'non_veg',
    servings: 2,
    preparationTime: 10,
  },

  // Dumplings
  {
    id: 'steamed-dumplings',
    name: 'Steamed Pork Dumplings',
    description: 'Tender pork-filled dumplings steamed to perfection',
    price: 5.99,
    image: '/menu-items/steamed-dumplings.jpg',
    category: 'Dumplings',
    spiceLevel: 'mild',
    vegType: 'non_veg',
    servings: 6,
    preparationTime: 12,
  },
  {
    id: 'vegetable-dumplings',
    name: 'Vegetable Dumplings',
    description: 'Fresh vegetable and mushroom filled dumplings',
    price: 4.99,
    image: '/menu-items/vegetable-dumplings.jpg',
    category: 'Dumplings',
    spiceLevel: 'mild',
    vegType: 'veg',
    servings: 6,
    preparationTime: 10,
  },
  {
    id: 'shrimp-dumplings',
    name: 'Shrimp Dumplings',
    description: 'Succulent shrimp and chive filled dumplings',
    price: 6.99,
    image: '/menu-items/shrimp-dumplings.jpg',
    category: 'Dumplings',
    spiceLevel: 'medium',
    vegType: 'non_veg',
    servings: 6,
    preparationTime: 12,
  },

  // Noodles
  {
    id: 'chow-mein',
    name: 'Vegetable Chow Mein',
    description: 'Stir-fried noodles with mixed vegetables and sesame oil',
    price: 5.99,
    image: '/menu-items/chow-mein.jpg',
    category: 'Noodles',
    spiceLevel: 'mild',
    vegType: 'veg',
    servings: 1,
    preparationTime: 12,
  },
  {
    id: 'chicken-chow-mein',
    name: 'Chicken Chow Mein',
    description: 'Tender chicken with crispy noodles and fresh vegetables',
    price: 7.99,
    image: '/menu-items/chicken-chow-mein.jpg',
    category: 'Noodles',
    spiceLevel: 'medium',
    vegType: 'non_veg',
    servings: 1,
    preparationTime: 13,
  },
  {
    id: 'shrimp-chow-mein',
    name: 'Shrimp Chow Mein',
    description: 'Succulent shrimp with garlic and noodles in a savory sauce',
    price: 8.99,
    image: '/menu-items/shrimp-chow-mein.jpg',
    category: 'Noodles',
    spiceLevel: 'medium',
    vegType: 'non_veg',
    servings: 1,
    preparationTime: 14,
  },
  {
    id: 'singapore-mei-fun',
    name: 'Singapore Mei Fun',
    description: 'Thin rice noodles with curry spices, vegetables, and shrimp',
    price: 8.99,
    image: '/menu-items/singapore-mei-fun.png',
    category: 'Noodles',
    spiceLevel: 'hot',
    vegType: 'non_veg',
    servings: 1,
    preparationTime: 14,
  },

  // Fried Rice
  {
    id: 'vegetable-fried-rice',
    name: 'Vegetable Fried Rice',
    description: 'Fluffy rice stir-fried with mixed vegetables and egg',
    price: 5.49,
    image: '/menu-items/vegetable-fried-rice.jpg',
    category: 'Fried Rice',
    spiceLevel: 'mild',
    vegType: 'veg',
    servings: 1,
    preparationTime: 10,
  },
  {
    id: 'chicken-fried-rice',
    name: 'Chicken Fried Rice',
    description: 'Tender diced chicken with jasmine rice and vegetables',
    price: 7.49,
    image: '/menu-items/chicken-fried-rice.jpg',
    category: 'Fried Rice',
    spiceLevel: 'mild',
    vegType: 'non_veg',
    servings: 1,
    preparationTime: 11,
  },
  {
    id: 'shrimp-fried-rice',
    name: 'Shrimp Fried Rice',
    description: 'Plump shrimp with fragrant fried rice and egg',
    price: 8.49,
    image: '/menu-items/shrimp-fried-rice.jpg',
    category: 'Fried Rice',
    spiceLevel: 'medium',
    vegType: 'non_veg',
    servings: 1,
    preparationTime: 12,
  },
  {
    id: 'special-fried-rice',
    name: 'Special Fried Rice',
    description: 'House special with chicken, shrimp, beef, and vegetables',
    price: 9.99,
    image: '/menu-items/special-fried-rice.jpg',
    category: 'Fried Rice',
    spiceLevel: 'medium',
    vegType: 'non_veg',
    servings: 2,
    preparationTime: 14,
  },

  // Chicken
  {
    id: 'kung-pao-chicken',
    name: 'Kung Pao Chicken',
    description: 'Diced chicken with roasted peanuts, peppers, and spicy sauce',
    price: 8.99,
    image: '/menu-items/kung-pao-chicken.png',
    category: 'Chicken',
    spiceLevel: 'hot',
    vegType: 'non_veg',
    servings: 2,
    preparationTime: 15,
  },
  {
    id: 'general-tso-chicken',
    name: "General Tso's Chicken",
    description: 'Crispy chicken in a sweet and spicy tangy sauce',
    price: 9.49,
    image: '/menu-items/general-tso.png',
    category: 'Chicken',
    spiceLevel: 'hot',
    vegType: 'non_veg',
    servings: 2,
    preparationTime: 15,
  },
  {
    id: 'teriyaki-chicken',
    name: 'Teriyaki Chicken',
    description: 'Glazed chicken with teriyaki sauce and sesame seeds',
    price: 8.49,
    image: '/menu-items/teriyaki-chicken.jpg',
    category: 'Chicken',
    spiceLevel: 'mild',
    vegType: 'non_veg',
    servings: 2,
    preparationTime: 14,
  },
  {
    id: 'lemon-chicken',
    name: 'Lemon Chicken',
    description: 'Crispy chicken with refreshing tangy lemon sauce',
    price: 8.49,
    image: '/menu-items/lemon-chicken.jpg',
    category: 'Chicken',
    spiceLevel: 'mild',
    vegType: 'non_veg',
    servings: 2,
    preparationTime: 13,
  },

  // Seafood
  {
    id: 'garlic-shrimp',
    name: 'Garlic Shrimp',
    description: 'Succulent shrimp sautéed with fresh garlic and ginger',
    price: 10.99,
    image: '/menu-items/garlic-shrimp.jpg',
    category: 'Seafood',
    spiceLevel: 'medium',
    vegType: 'non_veg',
    servings: 2,
    preparationTime: 14,
  },
  {
    id: 'honey-walnut-shrimp',
    name: 'Honey Walnut Shrimp',
    description: 'Crispy shrimp with candied walnuts in honey sauce',
    price: 11.99,
    image: '/menu-items/honey-walnut-shrimp.jpg',
    category: 'Seafood',
    spiceLevel: 'mild',
    vegType: 'non_veg',
    servings: 2,
    preparationTime: 16,
  },
  {
    id: 'black-pepper-fish',
    name: 'Black Pepper Fish',
    description: 'Fresh fish fillet with black pepper and aromatic spices',
    price: 12.99,
    image: '/menu-items/black-pepper-fish.jpg',
    category: 'Seafood',
    spiceLevel: 'hot',
    vegType: 'non_veg',
    servings: 2,
    preparationTime: 16,
  },

  // Beef
  {
    id: 'beef-broccoli',
    name: 'Beef & Broccoli',
    description: 'Tender beef with fresh broccoli in savory sauce',
    price: 9.49,
    image: '/menu-items/beef-broccoli.jpg',
    category: 'Beef',
    spiceLevel: 'mild',
    vegType: 'non_veg',
    servings: 2,
    preparationTime: 14,
  },
  {
    id: 'mongolian-beef',
    name: 'Mongolian Beef',
    description: 'Tender sliced beef with scallions and spicy sauce',
    price: 9.99,
    image: '/menu-items/mongolian-beef.jpg',
    category: 'Beef',
    spiceLevel: 'hot',
    vegType: 'non_veg',
    servings: 2,
    preparationTime: 15,
  },
  {
    id: 'mapo-tofu-beef',
    name: 'Mapo Tofu with Beef',
    description: 'Spicy tofu with minced beef in a numbing chili sauce',
    price: 9.99,
    image: '/menu-items/mapo-tofu.jpg',
    category: 'Beef',
    spiceLevel: 'very_hot',
    vegType: 'non_veg',
    servings: 2,
    preparationTime: 14,
  },

  // Vegetarian
  {
    id: 'vegetable-lo-mein',
    name: 'Vegetable Lo Mein',
    description: 'Soft noodles with mixed vegetables in light sauce',
    price: 5.99,
    image: '/menu-items/vegetable-lo-mein.jpg',
    category: 'Vegetarian',
    spiceLevel: 'mild',
    vegType: 'veg',
    servings: 1,
    preparationTime: 12,
  },
  {
    id: 'mapo-tofu',
    name: 'Mapo Tofu',
    description: 'Silky tofu in aromatic numbing and spicy sauce',
    price: 7.99,
    image: '/menu-items/mapo-tofu.png',
    category: 'Vegetarian',
    spiceLevel: 'very_hot',
    vegType: 'veg',
    servings: 2,
    preparationTime: 12,
  },
  {
    id: 'eggplant-garlic',
    name: 'Eggplant in Garlic Sauce',
    description: 'Tender eggplant with garlic, ginger, and chili peppers',
    price: 7.49,
    image: '/menu-items/eggplant-garlic.jpg',
    category: 'Vegetarian',
    spiceLevel: 'medium',
    vegType: 'veg',
    servings: 2,
    preparationTime: 13,
  },
  {
    id: 'vegetable-curry',
    name: 'Mixed Vegetable Curry',
    description: 'Fresh vegetables in a creamy curry sauce with cashews',
    price: 8.49,
    image: '/menu-items/vegetable-curry.jpg',
    category: 'Vegetarian',
    spiceLevel: 'medium',
    vegType: 'veg',
    servings: 2,
    preparationTime: 14,
  },

  // Desserts
  {
    id: 'mango-pudding',
    name: 'Mango Pudding',
    description: 'Smooth and creamy mango flavored pudding',
    price: 3.99,
    image: '/menu-items/mango-pudding.jpg',
    category: 'Desserts',
    spiceLevel: 'mild',
    vegType: 'veg',
    servings: 1,
    preparationTime: 0,
  },
  {
    id: 'almond-cookies',
    name: 'Almond Cookies',
    description: 'Crispy traditional almond cookies (3 pieces)',
    price: 2.99,
    image: '/menu-items/almond-cookies.jpg',
    category: 'Desserts',
    spiceLevel: 'mild',
    vegType: 'veg',
    servings: 3,
    preparationTime: 0,
  },
  {
    id: 'fried-banana',
    name: 'Fried Banana with Honey',
    description: 'Golden fried banana slices drizzled with honey',
    price: 4.49,
    image: '/menu-items/fried-banana.jpg',
    category: 'Desserts',
    spiceLevel: 'mild',
    vegType: 'veg',
    servings: 1,
    preparationTime: 8,
  },
  {
    id: 'lychee-sorbet',
    name: 'Lychee Sorbet',
    description: 'Refreshing lychee flavored sorbet',
    price: 3.49,
    image: '/menu-items/lychee-sorbet.jpg',
    category: 'Desserts',
    spiceLevel: 'mild',
    vegType: 'veg',
    servings: 1,
    preparationTime: 0,
  },

  // Drinks
  {
    id: 'mango-lassi',
    name: 'Mango Lassi',
    description: 'Refreshing yogurt-based mango drink',
    price: 2.99,
    image: '/menu-items/mango-lassi.jpg',
    category: 'Drinks',
    spiceLevel: 'mild',
    vegType: 'veg',
    servings: 1,
    preparationTime: 0,
  },
  {
    id: 'thai-iced-tea',
    name: 'Thai Iced Tea',
    description: 'Sweet and creamy Thai tea served over ice',
    price: 2.49,
    image: '/menu-items/thai-iced-tea.jpg',
    category: 'Drinks',
    spiceLevel: 'mild',
    vegType: 'veg',
    servings: 1,
    preparationTime: 0,
  },
  {
    id: 'jasmine-tea',
    name: 'Jasmine Tea',
    description: 'Aromatic jasmine tea',
    price: 1.99,
    image: '/menu-items/jasmine-tea.jpg',
    category: 'Drinks',
    spiceLevel: 'mild',
    vegType: 'veg',
    servings: 1,
    preparationTime: 0,
  },
  {
    id: 'lychee-juice',
    name: 'Fresh Lychee Juice',
    description: 'Freshly pressed lychee juice',
    price: 3.49,
    image: '/menu-items/lychee-juice.jpg',
    category: 'Drinks',
    spiceLevel: 'mild',
    vegType: 'veg',
    servings: 1,
    preparationTime: 0,
  },
];

export const CATEGORIES = [
  'Starters',
  'Soups',
  'Dumplings',
  'Noodles',
  'Fried Rice',
  'Chicken',
  'Seafood',
  'Beef',
  'Vegetarian',
  'Desserts',
  'Drinks',
];

export const TAX_RATE = 0.08;
export const DELIVERY_FEE = 2.99;
export const TAKEAWAY_FEE = 0;
export const DINE_IN_FEE = 0;

export const ESTIMATION_TIME = {
  delivery: 30,
  takeaway: 20,
  dine_in: 15,
};
